name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  # Make sure commit messages follow the conventional commits convention:
  # https://www.conventionalcommits.org
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: burrunan/gradle-cache-action@663fbad34e03c8f12b27f4999ac46e3d90f87eca # v3
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - name: Run Tests
        # https://stackoverflow.com/questions/50104666/difference-between-test-and-check-tasks-in-gradle
        run: ./gradlew check

  release:
    name: Release
    # needs: test
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      attestations: write
      artifact-metadata: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
      - uses: burrunan/gradle-cache-action@663fbad34e03c8f12b27f4999ac46e3d90f87eca # v3
      - id: setup-node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: lts/*
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - name: Decrypt Keystore
        # Keystore password should only contain alphanumeric characters.
        # Set `KEYSTORE` secret to the output of `gpg -c --armor keystore.jks`.
        # Set `KEYSTORE_PASSWORD` secret to the password used to encrypt the keystore.
        run: |
          echo "${{ secrets.KEYSTORE }}" > keystore.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_GPG_PASSWORD }}" --batch keystore.jks.asc > keystore.jks
          rm keystore.jks.asc
      - name: Release
        if: github.ref_name == 'main'
        run: npx --package=semantic-release --package=@semantic-release/exec --package=@semantic-release/git --package=@semantic-release/changelog semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_FILE: ${{ github.workspace }}/keystore.jks
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          KEYSTORE_KEY_ALIAS: key0
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      - name: Release (Dry Run)
        if: github.ref_name != 'main'
        run: npx --package=semantic-release --package=@semantic-release/exec --package=@semantic-release/git --package=@semantic-release/changelog semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_FILE: ${{ github.workspace }}/keystore.jks
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          KEYSTORE_KEY_ALIAS: key0
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      - name: Check if apk was generated
        run: |
          if ls app/build/outputs/apk/release/*.apk 1> /dev/null 2>&1; then
            echo "APK exists"
            echo "APK_EXISTS=true" >> $GITHUB_ENV
          else
            echo "APK does not exist"
            echo "APK_EXISTS=false" >> $GITHUB_ENV
          fi
      - name: Attest Build Provenance if apk exists
        if: env.APK_EXISTS == 'true'
        uses: actions/attest-build-provenance@e4d4f7c39adfa4c260fb5c147f0622000aa14b99 # v4
        with:
          subject-path: "app/build/outputs/apk/release/*.apk"
